#!/usr/bin/env bash
# Burnrate - Quick Start Script

echo "================================"
echo "🔥 BURNRATE - EXPENSE TRACKER 🔥"
echo "================================"
echo ""
echo "📍 Location: /Users/arpit/Desktop/Track"
echo ""
echo "Quick Commands:"
echo "=============="
echo ""
echo "1️⃣  Open in Xcode:"
echo "   cd /Users/arpit/Desktop/Track && open -a Xcode ."
echo ""
echo "2️⃣  Build from command line:"
echo "   cd /Users/arpit/Desktop/Track && xcodebuild -scheme Burnrate -configuration Debug"
echo ""
echo "3️⃣  Build and Run:"
echo "   cd /Users/arpit/Desktop/Track && xcodebuild -scheme Burnrate -configuration Debug -run"
echo ""
echo "4️⃣  Clean Build:"
echo "   cd /Users/arpit/Desktop/Track && rm -rf ~/Library/Developer/Xcode/DerivedData && xcodebuild -scheme Burnrate -configuration Debug"
echo ""
echo "📚 Documentation:"
echo "================"
echo "- README.md          → Features and architecture"
echo "- SETUP.md           → Build and setup guide"
echo "- PROJECT_SUMMARY.md → Detailed overview"
echo "- FILE_INVENTORY.md  → Complete file listing"
echo ""
echo "🎯 Key Features:"
echo "================"
echo "✅ Daily entry in < 2 seconds"
echo "✅ 12 expense categories"
echo "✅ Real-time total calculation"
echo "✅ Monthly reports with insights"
echo "✅ Category breakdown visualization"
echo "✅ Light/dark mode support"
echo "✅ Smooth animations"
echo "✅ Persistent storage"
echo ""
echo "📱 Keyboard Shortcuts (in Xcode):"
echo "=================================="
echo "Cmd+B    = Build"
echo "Cmd+R    = Run on simulator"
echo "Cmd+.    = Stop"
echo "Cmd+K    = Clear console"
echo "Cmd+Y    = Toggle breakpoints"
echo ""
echo "📊 App Structure:"
echo "================="
echo "Today Tab    → Add expenses, view daily total"
echo "Reports Tab  → View monthly reports and insights"
echo ""
echo "✨ Happy Expense Tracking! ✨"
echo ""
